name: Refresh News Content

# This workflow runs automatically every 15 minutes
on:
  schedule:
    # Runs every 15 minutes (*/15 means "every 15")
    # Format: minute hour day month day-of-week
    - cron: '*/15 * * * *'
  
  # Also allows you to run it manually from GitHub
  workflow_dispatch:

jobs:
  refresh-content:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Download your code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Install Python (the language your backend uses)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Step 3: Install the libraries your code needs
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      # Step 4: Run the RSS fetcher to refresh news
      - name: Run RSS fetcher
        env:
          # These values will come from GitHub Secrets
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          python rss_fetcher.py
      
      # Step 5: Show summary of what happened
      - name: Show completion message
        run: echo "✅ News refresh completed successfully!"